### ISSUE TITLE
No platform

### ISSUE THREAD

**Issue by warcanoid** [NorthernMan54/homebridge-wssensor#4]
I can not instal with sudo your plugin, withou sudo i get on end:make: 
Leaving directory '/home/pi/node_modules/mdns/build'
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-wssensor@0.1.40
added 115 packages from 126 contributors and audited 643 packages in 200.303s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~ $ npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-07-27T06_32_37_528Z-debug.log
pi@raspberrypi:~ $ npm audit
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-07-27T06_34_16_915Z-debug.log

**Comment by NorthernMan54** [comment]
Okay, let me look at this

You could try running npm audit from the directory the plugin is installed in, which may be node_modules/homebridge-wssensor depending on your setup

**Comment by NorthernMan54** [comment]
My gut says that this is some wackiness with a recent version of npm or node.

What version are you running of each?

**Comment by warcanoid** [comment]
Npm is 6.2.0 and node 3.2.0. If get this working, I will pay you!

**Comment by NorthernMan54** [comment]
Humm are those versions correct?

Typically node is 8.x.x or higher and npm is a  5.x

**Comment by warcanoid** [comment]
I updated now to node v10.7.0 and 6.1.0, found this with: node -v and npm -v

**Comment by warcanoid** [comment]
@NorthernMan54 let fix this, and then get paid. I am seriously

**Comment by NorthernMan54** [comment]
Okay I fixed the vulnerabilities listed, please re-install again

**Comment by warcanoid** [comment]
Thank you very much! It is now installed, the 4 platform-wssensor is loaded and get this on homebridge start:
[2018-7-28 15:38:24] [wssensor] Initializing wssensor platform...
[2018-7-28 15:38:24] [wssensor] homebridge-wssensor v0.1.41
[2018-7-28 15:38:24] [wssensor] Plugin - DidFinishLaunching
[2018-7-28 15:38:24] [wssensor] Number of Accessories: 0
[2018-7-28 15:38:24] [wssensor] url {"address":"::","family":"IPv6","port":8080}

But then nothing more happens. Adden all new to home app-no sensor button?
Also if I put port: 80, wont start homebridge, so I add port:  8080.
What now?

**Comment by NorthernMan54** [comment]
Did you build the nodemcu device?  And does it boot and connect to your wifi.

For devices, the plugin discovers the nodemcu devices and creates accessories as needed.

**Comment by warcanoid** [comment]
No, I have dlink dch-s150 motion sensor, and tplink nc450 camera

**Comment by NorthernMan54** [comment]
This plugin only works with the NodeMCU device that you need to build and not those devices.
